export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  LEADS: '/leads',
  CONTACTS: '/contacts',
  ACCOUNTS: '/accounts',
  DEALS: '/deals',
  ACTIVITIES: '/activities',
  CAMPAIGNS: '/campaigns',
  PRODUCTS: '/products',
  QUOTES: '/quotes',
  INVOICES: '/invoices',
  ORDERS: '/orders',
  FORECASTING: '/forecasting',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  NOT_FOUND: '/404',
  PERMISSION_DENIED: '/403',
} as const;
